### ISSUE TITLE
[DIN] Model Findings 

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#101]
Team Blue-marlin, During the execution of pipline  and trainer scripts of DIN, we have identified few minor bugs in the code. We will share the complete list of those bugs soon.

We have successfully performed the DIN model training . Following are our findings
1)	After performing spark data preparation steps. Around 10MB data size pickle files are created 
2)	Complete model training took around 5-6 hour on 16 core CPU machine
3)	Training/testing Best auc value as follow 
best train_gauc 0.8840  
test_gauc: 0.7660

**Comment by xun-hu-at-futurewei-com** [comment]
Hi, there,

This is great, let us have a discuss this Wed. 5pm PST. We would like you guys to check in the code to Github and merge it with our master branch.

Thanks,
-xun
