### ISSUE TITLE
[DIN] model placeholders explanation is required

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#104]
In CTR scroe prediction use case ,what does u,I,j,y,hist_i,sl and lr placeholders stand for .Would you please explain 

![image](https://user-images.githubusercontent.com/8120966/104278866-4ce56e80-54cf-11eb-97c7-e8226137309a.png)

**Comment by jimmylao** [comment]
self.u: user
self.i: positive sample (clicked)
self.j: negative sample (not clicked)
self.y: label (positive or negative)
self.hist_i: list of historical keywords (behavior)
self.sl: length of historical keywords
self.lr: learning rate
