### ISSUE TITLE
[DIN] Incompatible IMS response with inventory updater code

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#106]
Inventory updater send request to IMS service and in the response it get impression counts . 

![image](https://user-images.githubusercontent.com/8120966/105031554-7841fd80-5a7b-11eb-8616-78a84427407b.png)

As per the Inventory updater code IMS response should be in following format 

{
    "2020-07-01": {
        "h0": 0,
        "h1": 22528490,
        "h2": 1811051,
        "h3": 1525972
    },
    ...
    "2020-07-10": {
        "h0": 0,
        "h1": 22013470,
        "h2": 1103365,
        "h3": 1042275
    }
}

But actual IMS response is in following format (don’t contain the impression against h0,h2,h3…..)
{
    "2020-07-06": [
        {
            "total": 2,
            "h1": 2,
            "hr": 0
        }
    ]
},

Here h1 doesn’t represent the impression count against price category 1.It contain total impression count of the day …..

**Would you please suggest the required changes to make our code compatible existing response**

**Comment by radibnia77** [comment]
Please provide a sample of UCDoc from the predictions index that is used by IMS-Service.
