### ISSUE TITLE
Is advertiser can book exactly same inventories which by returned by PF?

### ISSUE THREAD

**Issue by zhentiwei** [Futurewei-io/blue-marlin#110]
in document "GDIN_intro.v2.pptx" mentioned as below

Advertiser selects some high-level search query criteria such as 
Geo regions
Gender
Age groups 
Number of impressions or clicks or CTR threshold
**PF recommends the best inventories in the system.
Advertiser books the returned inventories.**

so advertiser can book these exactly inventories which returned by PF, right?

Is PF can return and lock exactly inventories at same time?

for example, if PF will return 10% inventories, but once advertiser booked, system return another 10% inventories ?

Thanks for your confirmation.

**Comment by radibnia77** [comment]
pf-booking APIs locks inventories. 
If pf returns 1000 impressions, and an advertiser booked 500 of them then the im-service will immediately consider the booked amount. Although pf-graph API will know after the inventory-updater has run.

**Comment by xun-hu-at-futurewei-com** [comment]
There will be a gap between booking in IMS system vs inventory in PF, inventory-run will sync up the inventory between IMS and PF.

Thanks,
-xun

**Comment by zhentiwei** [comment]
ok, prodcut team expecting the same return amount of inventory.
