### ISSUE TITLE
Look Alike user similarity score threshold  

### ISSUE THREAD

**Issue by sanjaynirmal** [Futurewei-io/blue-marlin#120]
In the recent look-alike model where we are calculating the similarity score between a seed user and all users, Do we define any threshold score for similarity ?

**Comment by jimmylao** [comment]
Ideally, the similarity score (normalized cosine similarity) is a value between 0 and 1, a value higher than 0.5 shows strong similarities, so 0.5 can be used the similarity threshold.

In practice, each keyword may have weight different in a user's profile (some keywords may contribute to the majority of the clicks while other keywords have few clicks), thus the threshold may need to be adjusted accordingly based on the distribution of similarity in the population.
