### ISSUE TITLE
look-alike model keyword data

### ISSUE THREAD

**Issue by sanjaynirmal** [Futurewei-io/blue-marlin#121]
In the look-alike model we use keyword(s) against each ad creative for modelling. 
How will we get the keyword against each creative for the last 30 days at the time of model training ?

**Comment by jimmylao** [comment]
For a certain user
1. aggregate his/her daily keyword histogram, for example:
day1 -> kw1: 3, kw2: 2, kw3:5, ...
day2 -> kw2: 3, kw3: 1, kw5:3, ...
...
day30 -> kw2: 5, kw5: 8, kw7: 12, ...
2. discard the keyword count and concatenate keywords from day 1 to day 30 (or n) as the user's last 30 days behavoir history
kw1, kw2, kw3, ..., kw2, kw3, kw5, ..., ......, kw2, kw5, kw7, ...
<pre>(      day1      ) (     day2     )...,(     day30     )</pre>
