### ISSUE TITLE
[Look-alike] main_trainready script takes too long to run

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#130]
main_trainready.py script is taking more than 2 hour on a sample data of show log and click log . Actual production data will be more than the current . I doubt, we may face performance issue on production . Team blue-marlin, would you please suggest some optimization in this script  ??

Job Spark resources details are as follows 

- DRIVER_CORES=8
- DRIVER_MEMORY=16G
- EXECUTOR_MEMORY=16G
- EXECUTOR_CORES=8
- NUMBER_OF_EXECUTOR=45

**Comment by asheeshiit** [comment]
Team blue-marlin, would you please arrange one meeting regarding script optimization

**Comment by xun-hu-at-futurewei-com** [comment]
We will have a discuss session on BM's DL-Predictor performance on 3/1/2021 at 5pm PST, you are welcome to join us!

**Comment by radibnia77** [comment]
Can you please share the followings:

1. Which project is this issue related to?
2. How many records are in the main_trainready input table 
3. How many partitions does the main_trainready input table have?
4. What are the parameters in the config file?

**Comment by asheeshiit** [comment]
1. Which project is this issue related to:   look-alike model
2. How many records are in the main_trainready input table

![image](https://user-images.githubusercontent.com/8120966/109647460-51e5a680-7b7f-11eb-8e56-26a33e7f9d56.png)

3. How many partitions does the main_trainready input table have : no did_bucket (0,1)
4. What are the parameters in the config file? : default ( which blue-marlin team has shared)

following piece of code of main_trainready  is taking 5mins, 31sec  
![image](https://user-images.githubusercontent.com/8120966/109647607-8194ae80-7b7f-11eb-9a3c-c9852c848674.png)

following piece of code of main_trainready  is taking 32sec
![image](https://user-images.githubusercontent.com/8120966/109647670-92ddbb00-7b7f-11eb-961c-52ea64291f10.png)

**Comment by radibnia77** [comment]
Please let us know how the new code runs for the last step.

We could run the last step in 16 minutes using 110 cores.

**Comment by radibnia77** [comment]
Please use the same method and provide details of elapsed time after each command for main_tarinready.py so that we can find the performance bottleneck.
