### ISSUE TITLE
[look-alike]  Created TFRecords doesn't have data against some of the fields 

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#132]
I prepared the look-alike model data using main_tfrecords.py script . I found data against **keywords click_counts and show_counts** fields are not presant in TFRecord
![image](https://user-images.githubusercontent.com/8120966/109659440-af80ef80-7b8d-11eb-97a5-3ddecd1f1856.png)

I cross checked the hive table lookalike_02182021_trainready. I found there is mismatch in field name

![image](https://user-images.githubusercontent.com/8120966/109659465-b60f6700-7b8d-11eb-810a-336fdca15c3f.png)

**Comment by Faezehvaseghi** [comment]
The code has been updated.

**Comment by radibnia77** [comment]
The new code should take care of this issue.
