### ISSUE TITLE
Look-alike model saving

### ISSUE THREAD

**Issue by sanjaynirmal** [Futurewei-io/blue-marlin#138]
After running the trainer/train.py successfully. The output of this is a directory named "save_path". 
Contents of this directory are 
![image](https://user-images.githubusercontent.com/40193781/109960299-a0757b00-7d0e-11eb-86d9-20badf260db2.png)
this directory contains the checkpoint files but does not contain the model file in **.pb** format.
How can we generate the model file in .pb format ? 
We need to upload the .pb file on the MEP platform for model prediction.

**Comment by jimmylao** [comment]
The code to generate tensorflow serving servable model from trained checkpoint model (similar to the save_model.py in DIN model) is not in the repository yet, we'll upload the code soon and will let you know once available.

**Comment by jimmylao** [comment]
The code named 'save_model.py' is available now. Please use this code to generate TF servable model from your trained checkpoint (you may want to have a look sample command in the comment section at the beginning of the code)
