### ISSUE TITLE
Lookalike score generator issue

### ISSUE THREAD

**Issue by sanjaynirmal** [Futurewei-io/blue-marlin#143]
I have trained the lookalike mode and now I am trying to generate predictions from the trained model using score_generator.py
I am getting an error during the prediction part which is due to the following field
![image](https://user-images.githubusercontent.com/40193781/111317860-89c61100-868a-11eb-8391-5b246507022f.png)

when I went back to verify things and opened the gucdocs table, I did not find any such field.
Kindy help us in understanding this issue so that I can generate predictions from the model.

**Comment by rangaswamymr** [comment]
As per the discussion, It is agreed to implement below rules in data pipeline:

1. Exclude the users having impressions for less than x days ( 5 days for now) in training period considered.
2. Exclude the users having total number of impressions less than y ( 100 impressions for no)
3. Exclude the keywords and related logs whose contribution is less than z% (1% for now) of total traffic.

applying these rules will help in improving the accuracy of similarity score and reduce training and distance calculation time.
