### ISSUE TITLE
Look alike prediction issue

### ISSUE THREAD

**Issue by sanjaynirmal** [Futurewei-io/blue-marlin#145]
I was generating lookalike prediction and found two issues:

1. Look alike score for most of the users is in the range of 0.98 to 0.999
<img width="943" alt="smilarity_score" src="https://user-images.githubusercontent.com/40193781/111646658-d98e0f00-8827-11eb-84f8-98b956b406ca.png">

2. We don't get top 10 device ids(did) as output, we just get the scores. Do we need to implement this logic from our side.

**Comment by asheeshiit** [comment]
@jimmylao we are getting more than 90% of similarity score against each and every pair of user . it means, all the users available in corpus of user data are almost similar . In real world this won't happened . Would you please validate the code  ??

**Comment by xun-hu-at-futurewei-com** [comment]
Please provide more detail like what is the size of score matrix size, what is the score distribution etc.

**Comment by jimmylao** [comment]
@asheeshiit Can you please the did vs keyword score table?

**Comment by sanjaynirmal** [comment]
@jimmylao  Can you share the latest code where we are using the Euclidean distance approach to calculate the similarity rather than Cosine method. 
Since Euclidean distance is basically the shortest length between two vectors in N-dimensional space, how would we use it to generate a score between 0 and 1 ?

**Comment by jimmylao** [comment]
@sanjaynirmal We will update the code to replace cosine similarity with Euclidean similarity. The normalization of Euclidean similarity between 2 vectors to [0, 1] can be computed as follows.

Let: V<sub>1</sub> = [v<sub>11</sub>, v<sub>12</sub>, ..., v<sub>1n</sub>], V<sub>2</sub> = [v<sub>21</sub>, v<sub>22</sub>, ..., v<sub>2n</sub>], where n is the number of keywords

distance(V<sub>1</sub>,V<sub>2</sub>) = sqrt [(v<sub>11</sub>-v<sub>21</sub>)<sup>2</sup> + (v<sub>12</sub>-v<sub>22</sub>)<sup>2</sup> + ... + (v<sub>1n</sub>-v<sub>2n</sub>)<sup>2</sup> ]

Since upper bound for distance(V<sub>1</sub>,V<sub>2</sub>)  = sqrt(n), thus normalized_distance(V<sub>1</sub>,V<sub>2</sub>) = distance(V<sub>1</sub>,V<sub>2</sub>)  / sqrt(n)

so similarity(V<sub>1</sub>,V<sub>2</sub>)  = 1 - normalized_distance(V<sub>1</sub>,V<sub>2</sub>)

**Comment by sanjaynirmal** [comment]
@jimmylao Thanks for the detailed explanation on the Euclidean approach. 
This lookalike model output returns the score and not DID(device id) against a user at the time of prediction. 
DMP wants DIDs against a user for consumption. Kindly let us know if we need to do some changes in the code at our end or it can be done from your side in the current code also.

**Comment by jimmylao** [comment]
@sanjaynirmal The lookalike model is built on top of DIN model. 
The DIN model output return the score between did and keywords
| did | keyword<sub>1</sub> |  keyword<sub>2</sub> | ... | keyword<sub>n</sub> |
|---|---|---|---|---|
|did<sub>1</sub>| score<sub>11</sub>| score<sub>12</sub>| ... |score<sub>1n</sub>|
|did<sub>2</sub>| score<sub>21</sub>| score<sub>22</sub>| ... |score<sub>2n</sub>|
|...|...|...|...|...|
|did<sub>m</sub>| score<sub>m1</sub>| score<sub>m2</sub>| ... |score<sub>mn</sub>|

Based on the table above, the similarity table is generated between each pair of seed did and non-seed did
||seed did<sub>1</sub>|seed did<sub>2</sub>|...|seed did<sub>N</sub>|
|---|---|---|---|---|
|nonseed did<sub>1</sub>|similarity<sub>11</sub>|similarity<sub>12</sub>|...|similarity<sub>1N</sub>|
|nonseed did<sub>2</sub>|similarity<sub>21</sub>|similarity<sub>22</sub>|...|similarity<sub>2N</sub>|
|...|...|...|...|...|
|nonseed did<sub>M</sub>|similarity<sub>M1</sub>|similarity<sub>M2</sub>|...|similarity<sub>MN</sub>|

The lookalike model is computed based this 2nd table which quantifies the similarity from one did (user) against another did (user).

so, the situation you mentioned should have been covered in the code.

**Comment by sanjaynirmal** [comment]
@jimmylao Thanks for the update. 
I wanted to know whether this feature (DID as output) will be available in the upcoming release of your code ?

**Comment by Faezehvaseghi** [comment]
@sanjaynirmal 
In the similarity table, there is a column called "mean_score". You can get the DID as output with this two lines of code. 

fdf = df.select('did').orderBy(col('mean_score').desc())
did_list = [row[0] for row in fdf.select('did').collect()][0:extend]

extend is the number of DID that you need as an extended DID.

This part is already covered in validation.py

**Comment by Faezehvaseghi** [comment]
to change the Cosine similarity to Euclidean please do the following steps:

On file distance_table_list.py, in line 30 replace the "similarity"  formula with : 
similarity = 1 - (math.sqrt(sum([(item[i]-l2[i]) ** 2 for i in range(len(item))]))/math.sqrt(len(item)))


Also, in line 81, replace the line with :     df = df.withColumn('kws_norm_list', udf_tolist(col('kws')))

**Comment by sanjaynirmal** [comment]
@jimmylao @Faezehvaseghi 
We are now able to generate similarity score using Euclidean approach and the result seems better and much more dispersed than last time. 

<img width="946" alt="euclid" src="https://user-images.githubusercontent.com/40193781/113180531-757b3a00-926e-11eb-8009-eeac2de38a7f.png">

**Comment by Faezehvaseghi** [comment]
@sanjaynirmal  That's a good news. Thanks for updating us.

**Comment by xun-hu-at-futurewei-com** [comment]
Thank you all.

**Comment by sanjaynirmal** [comment]
@Faezehvaseghi 
we have run the validation.py script successfully and had generated DID score table named "lookalike_loaded_01112021"
This table has a column named did_bucket which is returning a constant value of 1, our expectation was it would return a list of similar DIDs
 
![image](https://user-images.githubusercontent.com/40193781/113668551-09fef580-96d0-11eb-8d89-f9d4f4b79a79.png)

**Comment by Faezehvaseghi** [comment]
You can ignore “did_bucket”. This is related to bucketing the data which gives the data some structure so it would be more manageable.  I assume we only have one or two buckets in our dataset, so you should see only 1, or 0.

**Comment by sanjaynirmal** [comment]
@Faezehvaseghi 
Yes, did_bucket has only two values 0 and 1.
So can we conclude that we are getting DID list via bucketing in front of every DID in the final output table.

**Comment by radibnia77** [comment]
did_bucket comes from lookalike_trainready table. It is not required for the application. It has 2 values because, in the config file, it is set to have 2 buckets for DIDs. We are going to remove this column from the application project. 

did_bucket is only used in lookalike data prep pipeline.
