### ISSUE TITLE
DL Predictor performance issue

### ISSUE THREAD

**Issue by rangaswamymr** [Futurewei-io/blue-marlin#154]
Hi,

The DL predictor script (main_spark_es.py) is taking too long to run with production data. 
This script is processing factdata table data for clustering the UCKyes is taking aproximately 5 hours for every 100 buckets. I think it is because there are many group by and join statements in this part of code. Can you please check this and suggest the optimizations? at this speed, it will take mote than 50 hours for fully processing the data and enter the prediction part.
The cluster size we used is 100 containers with 4 cores per executor, 16GB executor memory.

**Comment by rangaswamymr** [comment]
@jimmylao  can we discuss this issue on 2nd April, 8AM EST?

**Comment by radibnia77** [comment]
Hi,

There are two areas that we need to work on.

1. The spark-submit command and the cluster spec.

Can you tell us what is your spark-submit command? 
How many nodes are available to use?
What is the spec of each node? For example, the spec of one of our nodes is:

Total Vmem allocated for Containers = 157 GB
Total Pmem allocated for Containers = 75 GB
Pmem enforcement enabled = true
Total VCores allocated for Containers = 25

2. Use repartitioning in the code. The goal is to perform groupBy and Join with the least amount of data shuffling.
We are working on the code to add this feature.

**Comment by rangaswamymr** [comment]
@radibnia77 , in our test, we did not find any improvement in data processing time after adding repartitioning. it took exactly same time - 1 hour 38 mins for processing 300 buckets of data with 30 executors. 

However, the data shuffle read/write for the task before repartitioning was 219GB and after repartitioning, it changed to 114GB.

**Comment by radibnia77** [comment]
Let’s review the case we have here and please correct me if I am wrong.

1. We have a performance issue with main_spark_es.py.
	a.	It took 50 hours to process 1000 buckets using 100 executors (4 cores, 20G RAM each)

2. The input table is Factdata with the following spec.
	a. It is partitioned and bucketized by bucket-id and day.
	b. All the slot ids are valid.
	c. Residence and IP-location information exists in Factdata.
	d. Factdata only has the days that are required by the model duration parameter.
	
The Factdata we had did not have residence and IP-location, also it was not partitioned and had invalid slot-ids so we had to run an extra process on it. That extra process is not part of main_spark_es.py.  Let us know of the conditions of your Factdata.

3. You mention in the above comment that after repartitioning, the processing time for 300 buckets with 30 executers is 100 min. In this case, it is pretty good, it means that if you are using 100 executers with 1000 buckets it would take only 1.5 hours. So clearly, I am missing something here, so please tell me what it is.


We have a test on our end too. After the initial run, I saw that repartitioning did not help with processing time. 

At this time I guess the reason that you see very high processing time on main_spark_es is that your Factdata either
1. has invalid slot-ids (lots of invalid records) or 
2. has more days that are required by the model or 
3. is not partitioned by day or bucket-id.

**Comment by radibnia77** [comment]
Can you please try processing 1000 buckets with 30 executers (4 cores and 20G RAM), same conditions that you ran for 300 buckets?

**Comment by rangaswamymr** [comment]
@radibnia77 let me answer point by point in your post.

1. That is right. But, please note that this is in production environment.
2.  About fact data table:
     a. Yes, table is partitioned by day and bucket ids.
     b. Not sure what you mean by all slot ids are valid. how do you define invalid slot ids here?
     c. I have not verified this, will check and confirm.
     d. Factdata table in production has more data than what is used in algorithm.
3. Our test with repartitioning is not on production. it is on test environment with the amount of data in factdata table in test environment is way less than production.  So, we cannot compare the time taken in test environment to that of production.

Can we have a discussion on this topic on 8th April 6pm PST?

**Comment by xun-hu-at-futurewei-com** [comment]
See comment below:
2b: We have a lot of ad slot ids, only few of them are stable ad slot ids. Valid ad slot ids mean stable ad slot ids.

Please check twitter, I already scheduled a meeting on 4/8/2021 at 6pm PST to discuss the performance issue.

**Comment by radibnia77** [comment]
Please try the following on your dataset and let us know about the time it took.

Script main_spark_es.py: executer=30, cores=4, memory=16G
Bucket step: 30
Bucket size: 1000
Time for whole data: ?
Notes:
     1. Focus on the while loop.
     2. Slot id filtering happens during while loop (already exists)
     3. Add df_dist.cache()
     4. Use take(1) instead of the count at the end of each iteration in the loop.

**Comment by radibnia77** [comment]
Are there any updates on the run for bucket-size=1000?

**Comment by radibnia77** [comment]
Can you also test a run for 300 buckets (30 executers, 4 cores, 16G) but with no cache? Remove every cache command except for df_dist?

**Comment by zhentiwei** [comment]
We will check tomorrow, since Today is in Holiday here ...

**Comment by radibnia77** [comment]
Please try the following tests on your dataset and let us know about the time it took.

Run (1)
Script main_spark_es.py: executer=30, cores=4, memory=16G
Bucket step: 30
Bucket size: 150, 300, 1000
Time for whole data: ?
Notes:
1. Focus on the while loop.
2. Slot id filtering happens during while loop (already exists)
3. Add df_dist.cache() and df_dist = df_dist.repartition("uckey")
4. Add repartitioning for uckey ( df = df.repartition("uckey") ) in the loop and 
5. Have cache for df_uckey_cluster.cache() and df_prediction_ready.cache() in the loop (existing code)
6. Don't have action inside the loop just one count() after the loop, use count() not take()

Run (2)
Script main_spark_es.py: executer=30, cores=4, memory=16G
Bucket step: 30
Bucket size: 150, 300, 1000
Time for whole data: ?
Notes:
1. Focus on the while loop.
2. Slot id filtering happens during while loop (already exists)
3. Add df_dist.cache() and df_dist = df_dist.repartition("uckey")
4. Add repartitioning for uckey ( df = df.repartition("uckey") ) in the loop and 
5. Remove cache for df_uckey_cluster.cache() and df_prediction_ready.cache() in the loop (no inside loop cache)
6. Don't have action inside the loop just one count() after the loop, use count() not take()

The first goal is to focus on one run and check the linearity of the performance for different bucket-size. If it is not linear, we need to be able to explain it.

The second goal is to test the same runs with no cache inside the loop.

**Comment by rangaswamymr** [comment]
@radibnia77 an update from our test today, after removing the cache and all actions inside loop, we are now able to execute 500 buckets in 1 hour and 30 mins. earlier, it was taking around 15 hours. 
But, when we try with 100 buckets, we are not able to execute, we are getting "out of memory" error. 

erFactory. | org.apache.hadoop.hive.ql.session.SessionState.setAuthorizerV2Config(SessionState.java:795)
[Stage 6:(0 + 0) / 560550][Stage 7:(0 + 0) / 560550][Stage 8:(0 + 0) / 560550]Exception in thread "dag-scheduler-event-loop" java.lang.OutOfMemoryError: GC overhead limit exceeded

we are getting this error even after increasing executor memory from 16 to 20GB.

if we increase the executor memory too much, we will not get enough executors assigned. we will probably need to consider to save data to hdfs after processing 250 buckets and reset the DAG. we will analyze this internally and update you tomorrow.

**Comment by erictsai-fw** [comment]
Here are the times for the performance tests that we've done so far.  It does appear that the loop portion has linear or better than linear performance, at least on our data.  I'm going to run some tests on the post-loop portion to test its linearity.

[performance-records.xlsx](https://github.com/Futurewei-io/blue-marlin/files/6319872/performance-records.xlsx)

**Comment by radibnia77** [comment]
That's good news.

Please look up the error to find the exact reason. The error comes from the dag scheduler. 
Also, let us know how you are planning to rest the DAG, which command are you going to use?

**Comment by rangaswamymr** [comment]
@radibnia77 , we executed with bucket size 1000, bucket step 30 as discussed today and we are getting a spark error after running for more than one hour. Error log is shared to you by zhentiwei. Please check and let us know if any further changes needed.

**Comment by radibnia77** [comment]
What is the Spark version?

**Comment by radibnia77** [comment]
I looked into the log file. It seems the problem is not a memory issue. It is a timeout error. 
This was an issue for Spark < 2.3 
https://issues.apache.org/jira/browse/SPARK-18838

If your Spark version is less than 2.3, it is probably the case. I am running 2.3.3 version. Please let me know of your Spark version.

Please try by setting spark.scheduler.listenerbus.eventqueue.size to higher numbers.
The default of spark.scheduler.listenerbus.eventqueue.size is 10,000, change it to 50,000 and make sure driver memory is 32G or higher.

I am running a very big job to see if I can reproduce the error. I put the loop in another loop, to have a total iteration of 30. You have 34 iterations 1000/30. So far things are smooth.

Please try bucket-step=20 and bucket-size=1000, this will cause less load. 

I am still doing some research but let me know of your Spark version so that I can focus on it.

**Comment by radibnia77** [comment]
Nevertheless, it seems that we need to break the large job, it is a safe bet for us to handle a larger amount of data. 

To break the large job, we need to save df_prediction_ready to HDFS in each iteration. For example, after processing 30 buckets we save the results. We still need to groupBy for each iteration, otherwise, it is not going to fly. 

Before saving the df_prediction_ready into HDFS, we need to add cluster_bucket_id to it, the same concept as bucket_id.

After the first loop is done, we need a second loop to go over cluster_bucket_ids and groupBy again. 

I am going to work on the changes tomorrow, meanwhile, you guys can start implementing the code as well, and then we sync.  I don't think there is a big change so we can finish it in one day. Let me know what you think.

**Comment by rangaswamymr** [comment]
@radibnia77 after changing below items, its working fine now.

1. Before exiting the program, added sc.stop() 
2. changed the spark configurations to below values. 

DRIVER_CORES=8
DRIVER_MEMORY=32G
EXECUTOR_MEMORY=20G ( if was 16GB)
EXECUTOR_CORES=5 ( it was 4)
NUMBER_OF_EXECUTOR=30
MEMORY_OVERHEAD=10G ( it was 5GB)
MAX_RESULT_SIZE=10G ( it was 5GB)

we tried to execute the loop with bucket size 1000 and bucket step 30 and 35, it worked for for both bucket steps and got the count of df_prediction_ready: 286945.  It took ~3 hours to complete the while loop execution.

we will try to implement these changes in production also and update you on status.

Thank you very much for your support.

**Comment by xun-hu-at-futurewei-com** [comment]
This is really a good news, let us discuss it in today's meeting.

Thanks,
-xun

**Comment by asheeshiit** [comment]
@jimmylao 
we would like to discuss our finding. would you please join the meeting , using link ,shared below
Join (External) : https://welink-meeting.zoom.us/j/213186080
