### ISSUE TITLE
Performance Forecasting Status

### ISSUE THREAD

**Issue by zhentiwei** [Futurewei-io/blue-marlin#164]
Any new features will be added in Performance Forecasting Model?
for example, add new feature in IMS side for booking purpose...

Can share to us any new progress on Performance Forecasting?

Thanks a lot.

**Comment by radibnia77** [comment]
There is no new API for Performance Forecasting. 
Performance Forecasting has 2 API as introduced previously
1. Graph API
2. Booking API

Although, there will be a new API for IMS-services which is called batch-booking.
