### ISSUE TITLE
Found Inf or NaN global norm

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#17]
**Tensor had NaN values**
I got following exception during the trainning of predictor_dl_model .I tried to trained the tensorflow model in eager execution mode, but didn't enough clue. Can you please help me in identifying the issue

Command :    python trainer/trainer.py config.yml 

Exception:

![image](https://user-images.githubusercontent.com/8120966/74132310-52c23800-4c0c-11ea-972c-00683fcb2646.png)
![image](https://user-images.githubusercontent.com/8120966/74132415-8a30e480-4c0c-11ea-8410-e8337d4199da.png)

Trainer Configurations:

![image](https://user-images.githubusercontent.com/8120966/74132632-fa3f6a80-4c0c-11ea-8586-7c983164ffd0.png)

HyperParam(trainer/hparams.py):

![image](https://user-images.githubusercontent.com/8120966/74132738-24912800-4c0d-11ea-922f-ca00dcf8d699.png)

**Comment by jimmylao** [comment]
The issue is likely caused by input data.  There are 3 input data files named "feeder_meta.pkl", "feeder.cpt.index", "feeder.cpt.data-00000-of-00001" under (default setting) data/vars. It looks like there are some exception values (inf or nan) in input data which triggers the error message. You may either
1. double check the input data is valid
or
2. upload these 3 files so that I can reproduce the issue and have more detailed information.

**Comment by jimmylao** [comment]
For your convenience, we'll upload some sample reference data ("feeder_meta.pkl", "feeder.cpt.index", "feeder.cpt.data-00000-of-00001") in Model/predictor_dl_model/predictor_dl_model/data/vars. Once the data has been copied to the "data/vars" folder on your local machine, please try to run the command (python trainer/trainer.py config.yml) again to see if it works or not. If it works, you may want to compare the difference between the reference data and your data.
Please feel free to let us know if it still does not work.

**Comment by saritpg** [comment]
Please upload the feeder files for cross-checking this issue.

**Comment by jimmylao** [comment]
Sorry for the delay. The feeder files have been uploaded in Model/predictor_dl_model/predictor_dl_model/data/vars.
Please feel free to let us know if it still does not work.
