### ISSUE TITLE
WeChat Look alike model research paper

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#171]
@jimmylao  WeChat has proposed attention based look-alike model to get the similar users ... As we have discussed , i am attaching the research paper . PFA

[RealtimeAttentionBasedLookalikeModelforRecommenderSystem.pdf](https://github.com/Futurewei-io/blue-marlin/files/6622313/RealtimeAttentionBasedLookalikeModelforRecommenderSystem.pdf)

**Comment by jimmylao** [comment]
Thanks for sharing the information
