### ISSUE TITLE
Updated code for DL predictor

### ISSUE THREAD

**Issue by rangaswamymr** [Futurewei-io/blue-marlin#172]
Hi,

In last weekly meeting, you mentioned about the release of updated version of DL predictor code ( pipeline part). Can you please clarify on when we can expect this new version of code to be committed in git?

**Comment by xun-hu-at-futurewei-com** [comment]
We already verified the model with current pipeline, and we will release code this Monday.

Thanks,
-xun

From: Rangaswamy M R ***@***.***>
Sent: Sunday, June 13, 2021 7:42 PM
To: Futurewei-io/blue-marlin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Futurewei-io/blue-marlin] Updated code for DL predictor (#172)


Hi,

In last weekly meeting, you mentioned about the release of updated version of DL predictor code ( pipeline part). Can you please clarify on when we can expect this new version of code to be committed in git?

-
