### ISSUE TITLE
Running trainer.py shows nan values for MAE and SMAPE

### ISSUE THREAD

**Issue by saritpg** [Futurewei-io/blue-marlin#18]
**Describe the bug**
While running trainer.py for the model, the output for model training update shows nan/nan values for MAE and SMAPE

**To Reproduce**
I ran the trainer.py file with the config.yml file as args. The tfrecord hdfs input file exists in the given location.

**Expected behavior**
I expected to see some numerical values for these metrics.

**Screenshots**
![image](https://user-images.githubusercontent.com/12243267/74132990-99fcf880-4c0d-11ea-97ca-476999584c5c.png)

Although please see this below screenshot if this could be the underlying cause:
![image](https://user-images.githubusercontent.com/12243267/74133063-bef16b80-4c0d-11ea-9971-c5fb8dbfa896.png)

**Desktop (please complete the following information):**
 - Linux Hadoop environment

**Comment by jimmylao** [comment]
It's not an error, but a display issue. While computing MAE and SMAPE error, the first 2 numbers (showing nan above) are validation error, the third number is the training error. It is showing "nan" for the first 2 numbers indicating there's no validation during this training run.
