### ISSUE TITLE
Reg the Design Document

### ISSUE THREAD

**Issue by zhentiwei** [Futurewei-io/blue-marlin#19]
Dear, very nice meeting.

Can anyone can share the design document for this project?

One high level design document also fine , this can help us to understand the overall system architecture :)

High appreciated for your sharing.

**Comment by zhentiwei** [comment]
Dear, I have one example, Can you please check this document, this is what we want to have.

High appreciated for your sharing.
![Predicto1](https://user-images.githubusercontent.com/58080300/75320940-c8c5d080-5895-11ea-998e-0f639feec5e7.png)


![Predicto3](https://user-images.githubusercontent.com/58080300/75320986-dbd8a080-5895-11ea-8e78-62b210de7693.png)
![Predicto4](https://user-images.githubusercontent.com/58080300/75320991-e09d5480-5895-11ea-8d54-180a15b391b6.png)
![Predicto5](https://user-images.githubusercontent.com/58080300/75321004-e5fa9f00-5895-11ea-814d-870c3571cbcf.png)

**Comment by jimmylao** [comment]
![image](https://user-images.githubusercontent.com/60371672/75403550-0f3b1f80-58d6-11ea-8a3a-82479c4b72e0.png)
The figure illustrates relationship of major functions for the model. Corresponding comments are added in model.py.
More comments as well as plots of more detailed information are coming in these couple of days.

**Comment by zhentiwei** [comment]
Awesome !  We are looking forward to the overall architecture, I think there should be one document to systematically explain this architecture :)
