### ISSUE TITLE
clarifications on DL pipeline script: main_filter_si_region_bucket.py

### ISSUE THREAD

**Issue by rangaswamymr** [Futurewei-io/blue-marlin#203]
@radibnia77 , i have few questions on below code in main_filter_si_region_bucket.py. can we have a short discussion today? 23rd Sept 8:30AM PST?

df = df.join(mapping_df, df.ipl == mapping_df.ipl_new, how='left')  -- why join on   df.ipl == mapping_df.ipl_new ?
df = df.withColumn('uckey', new_uckey(array(df.uckey, df.ipl_old))) -- shouldnt this be df.ipl_new instead of df.ipl_old?

**Comment by radibnia77** [comment]
in the mapping table, the original ipl column is named 'NEW', and the virtual ipl column is named 'OLD'
