### ISSUE TITLE
lookalike application with gpu

### ISSUE THREAD

**Issue by radibnia77** [Futurewei-io/blue-marlin#213]
Please provide a presentation to show the design and sample code on how to use GPU to calculate the similarity table for the lookalike application.

**Comment by asheeshiit** [comment]
HI blue-marlin,  
please find the code , which can calculate user to user distance on GPU

[distance_calculation_using_gpu.txt](https://github.com/Futurewei-io/blue-marlin/files/7390593/distance_calculation_using_gpu.txt)



Soon we will upload the PPT , with high-level overview of code
