### ISSUE TITLE
Impressions are set to 0 while denoising the timeseries

### ISSUE THREAD

**Issue by rangaswamymr** [Futurewei-io/blue-marlin#220]
@radibnia77  in main_cluster.py file, denoise function, below code (in bold) is setting most of the time series values to 0. 

`   df = df.withColumn('nonzero_p', udf(
        lambda ts: 1.0 * sum(ts) / len([_ for _ in ts if _ != 0]) if len(
            [_ for _ in ts if _ != 0]) != 0 else 0.0, FloatType())(df.ts))
    df = df.withColumn('nonzero_sd', udf(lambda ts: stdev([_ for _ in ts if _ != 0]))(df.ts))

    df = df.withColumn('ts', udf(lambda ts, nonzero_p: [i if i and i > (nonzero_p / percentile) else 0 for i in ts],
                                 ArrayType(IntegerType()))(df.ts, df.nonzero_p))
    **df = df.withColumn('ts', udf(lambda ts, nonzero_sd: [i if i and i < (nonzero_sd * 2) else 0 for i in ts],
                                 ArrayType(IntegerType()))(df.ts, df.nonzero_sd))**`

as an example, if we take below time series and run this code, its setting all ts elements to 0 because the ts impressions are greater than 2*nonzero_sd. 

sample ts: [0, 0, 0, 0, 0, 5840, 5952, 4177, 2940, 3656, 4995, 4870, 4609, 3808, 3821, 3331, 4795, 5388, 4900, 6059, 4480, 3360, 3172, 3502, 4157, 0, 4641, 4579, 4215, 4418, 4300, 5582, 0, 4646, 5580, 4301, 4064, 4482, 4023, 0, 4680, 4225, 3766, 3911, 3110, 4085, 5196, 4542, 3624, 3279, 4331, 3559, 2988, 3392, 3104, 3660, 4200, 4268, 0, 4226, 3508, 3749, 4164, 3668, 3502, 4244, 4405, 4391, 3780, 4346, 3786, 3756, 4546, 4207, 4475, 4002, 4366, 3481, 3586, 3162, 0, 4774]
nonzero_p: 4176.208333333333
nonzero_sd: 704.0879614042312
result after checking i > (nonzero_p / percentile) : [0, 0, 0, 0, 0, 5840, 5952, 4177, 2940, 3656, 4995, 4870, 4609, 3808, 3821, 3331, 4795, 5388, 4900, 6059, 4480, 3360, 3172, 3502, 4157, 0, 4641, 4579, 4215, 4418, 4300, 5582, 0, 4646, 5580, 4301, 4064, 4482, 4023, 0, 4680, 4225, 3766, 3911, 3110, 4085, 5196, 4542, 3624, 3279, 4331, 3559, 2988, 3392, 3104, 3660, 4200, 4268, 0, 4226, 3508, 3749, 4164, 3668, 3502, 4244, 4405, 4391, 3780, 4346, 3786, 3756, 4546, 4207, 4475, 4002, 4366, 3481, 3586, 3162, 0, 4774]
result after checking i < (nonzero_sd * 2) : [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

please check if you have used the same code in your tests or if any change in it.

**Comment by jimmylao** [comment]
@rangaswamymr lets have a discussion about it. Please join zoom meeting
https://futurewei.zoom.us/j/6930705942

**Comment by radibnia77** [comment]
Please remove 
**df = df.withColumn('ts', udf(lambda ts, nonzero_sd: [i if i and i < (nonzero_sd * 2) else 0 for i in ts],
                             ArrayType(IntegerType()))(df.ts, df.nonzero_sd))**`

In our testing, the above line was not effective because the type of udf in the following code was not set and nonzero_sd type became string. 

the statement 1000 < '1' is True in python

` df = df.withColumn('nonzero_p', udf(
lambda ts: 1.0 * sum(ts) / len([_ for _ in ts if _ != 0]) if len(
[_ for _ in ts if _ != 0]) != 0 else 0.0, FloatType())(df.ts))
