### ISSUE TITLE
dense-uckey for slot-ids

### ISSUE THREAD

**Issue by radibnia77** [Futurewei-io/blue-marlin#225]
Share the output of the following command for the following slot-ids

select count(distinct uckey) from dlpm_<>_tmp_distribution where uckey like '%<slot-id>%' and ratio=1;

slot-id---------->                                                     uckey-count
66bcd2720e5011e79bc8fa163e05184e---------->10462
71bcd2720e5011e79bc8fa163e05184e---------->	    2487
7b0d7b55ab0c11e68b7900163e3e481d---------->	    8792
a47eavw7ex---------->				                    9111
a8syykhszz---------->				                    162
b6le0s4qo8---------->				                    8995
e351de37263311e6af7500163e291137---------->	    7754
l03493p0r3---------->				                    6506

**Comment by rangaswamymr** [comment]
Data from our side:

slot-id----------> uckey-count
66bcd2720e5011e79bc8fa163e05184e---------->10393
71bcd2720e5011e79bc8fa163e05184e---------->  2434
7b0d7b55ab0c11e68b7900163e3e481d----------> 8721
a47eavw7ex----------> 9062
a8syykhszz----------> 154
b6le0s4qo8----------> 8923
e351de37263311e6af7500163e291137----------> 7657
l03493p0r3----------> 6421
