### ISSUE TITLE
Contribute model files

### ISSUE THREAD

**Issue by radibnia77** [Futurewei-io/blue-marlin#226]
Please contribute model and feeder files and also model-status pickle files for dlpm.
Add them to blue-marlin/Model/predictor-dl-model/saved-models/

**Comment by rangaswamymr** [comment]
@radibnia77 @jimmylao  i think there is lot of improvement in accuracy after using the model you shared. below are the details. 
The last column ('Predicted impr using BMmodel') has the predicted impressions using your model and 4th column (pred_impr_original ) has the original predicted impressions i shared yesterday.

day | uckey_new | actual_impr | pred_impr_original | BM team impressions | Predicted impr using BMmodel
7/22/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3114 | 5667 | 4089 | 3893
7/23/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3764 | 6042 | 4164 | 4215
7/24/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3753 | 5899 | 4236 | 4313
7/25/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3296 | 5877 |   | 4724
7/26/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3355 | 5549 |   | 4474
7/27/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3192 | 5012 |   | 3935
7/29/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3802 | 4272 |   | 4620
7/30/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3265 | 4482 | 3628 | 4028
7/31/2021 | native,b6le0s4qo8,4G,g_f,5,CPC,,1156320000 | 3346 | 5102 |   | 4379

**Comment by radibnia77** [comment]
We also uploaded checkpoints data in the same location. Please use them to train a new model and verify the predictions. If predictions are good, it means that your trainer is working fine and we need to go back and fix discrepancies with the data. Otherwise, we need to check the trainer code and its settings.

**Comment by radibnia77** [comment]
The feeder_files.zip size is about 2M, while it should be about 27M. Seems uckeys are missing here.

**Comment by rangaswamymr** [comment]
@radibnia77 @jimmylao  After yesterdays discussion, i found an issue in below code and its fixed now. but, even after fixing this, the dense uckeys are not matching with your list. 
Can we discuss it today and continue our analysis? please share your meeting id.

old code in main_outlier.py:
x[i] = (x[i - 1] + x[i + 1]) / 2

new code in main_outlier.py:
x[i] = int((x[i - 1] + x[i + 1]) / 2)

type conversion was causing issue and after converting the values to int, its ok now.

**Comment by rangaswamymr** [comment]
@radibnia77 let us have a discussion on this issue on 15/Dec @5pm PST.

**Comment by jimmylao** [comment]
@rangaswamymr there will be some schedule conflict at 15/Dec @5pm PST, lets have a open discussion regarding statistics on Dec 16, 8am PST
