### ISSUE TITLE
DIN Lookalike: Data Sampling understanding #28

### ISSUE THREAD

**Issue by srinaginikonduru** [Futurewei-io/blue-marlin#248]
[](https://user-images.githubusercontent.com/51720850/149085830-1a5398ab-b943-41a1-9450-11eb1e3f9561.png)Hello Jimmy,

We would like to understand how you did sampling in the lookalike_build_dataset.py script.

image

It would be great if you can share an informal description of this sampling method, so that we can reproduce it at our end.

Thanks.

**Comment by srinaginikonduru** [comment]
Please find the attach pdf file for an illustration of sample extraction process used.
[sample-extraction-example.pdf](https://github.com/apache/incubator-bluemarlin/files/7855939/sample-extraction-example.pdf)

**Comment by srinaginikonduru** [comment]
https://github.com/jimmylao
Thanks for the document, Can we have a session on the understanding of this pdf that you have shared above.
It would be better if we can have a separate session for this today, some hours before the scheduled weekly meeting as per your convenience.

**Comment by jimmylao** [comment]
@srinaginikonduru Sure, we can have a short meeting tomorrow. Please go ahead and book some meeting time tomorrow.
