### ISSUE TITLE
question regarding the data input in seq2seq model

### ISSUE THREAD

**Issue by saritpg** [Futurewei-io/blue-marlin#27]
Hi,

First of all, thank you for the wiki. Quite informative. My question is related to the data input. The features + time series data is used as data input into the model. However, I am confused regarding the non-time series features. My understanding was that Seq2seq models take only time series data or sequential data as input. How do the the other non-time series features included in the model? How does seq2seq model use it? What are the input dimensions?

Can you please explain the data input part? Thanks.

**Comment by jimmylao** [comment]
In the simplest form, input data for seq2seq model is the only time-series data. The input for this seq2seq model is still sequential data but in the form of time-series data + non-time-series features, the major sequential input data is a 3D matrix with the shape of 

_batch_ x _train_window_ x _num_of_features_
 
where:
_batch_ is batch size
_train_window_ is the length of the sequence in the time domain
_num_of_features_ is the number of total features for each time-spot of a specific row, i.e. 24 in the current setting.

Initial time-series feature (hits) contributes only 1 in 24 features, other 23 features include dow, age, si, network, gender, ...
Such input feature definition will enable the model to take both time-series and 
non-time-series (row specific features) into consideration.

**Comment by saritpg** [comment]
Thanks. If I understand correctly, the data would look like this?

[[t1, age, si, dow, gender,...][t2, age, si, dow, gender,...][t3, age, si, dow, gender,...][..][...]], where t is time series data, and t1, t2, ...t90 are the time steps. Each time step includes all the other non-time series features.

Let me know if this is the correct way to input the data, or if there is another way to do it.

**Comment by jimmylao** [comment]
Yes, it is correct
