### ISSUE TITLE
Error while executing tfreader.py

### ISSUE THREAD

**Issue by saritpg** [Futurewei-io/blue-marlin#28]
**Describe the bug**
While running the tfreader.py file, I ran into this error.

Please note that the all the python packages are of the same version as mentioned in requirements.txt.

**Screenshots**

![test](https://user-images.githubusercontent.com/12243267/76208019-e34c6200-6224-11ea-80dd-1fc5565ff38f.png)

**Comment by saritpg** [comment]
zz

**Comment by xunh** [comment]
what is the reason to close it?Sent from my Huawei phone-------- Original message --------From: saritpg <notifications@github.com>Date: Mon, Mar 9, 2020, 05:00To: Futurewei-io/blue-marlin <blue-marlin@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [Futurewei-io/blue-marlin] Error while executing tfreader.py (#28)Closed #28.

**Comment by saritpg** [comment]
Found the issue. The data was not generated properly leading to tensorflow error.

**Comment by xun-hu-at-futurewei-com** [comment]
Is it related to the pipeline? Please provide the detail or update the code with pull request.

**Comment by saritpg** [comment]
Related to my environment, where there were issues with read/write access. Not related to the blue-marlin code.
