### ISSUE TITLE
Fact Data Analysis

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#29]
**Skewed data Issue**
I have skewed data. 98% of data have only one data point in 90 days time series. Would you please guide me, how to train model using blue-marlin deep learning solution ??

I am sharing the statistics of my data in excel file 
PFA: [fact data analysis.xlsx](https://github.com/Futurewei-io/blue-marlin/files/4310999/fact.data.analysis.xlsx)

**Comment by jimmylao** [comment]
[fact.data.analysis.xlsx](https://github.com/Futurewei-io/blue-marlin/files/4320834/fact.data.analysis.xlsx)

Some analysis (plots) was added to your spreadsheet as attached. Based on the daily data, sparsity was computed for each day which agrees with what you described.
The value of variable 'impr_sum' looks too small, would you please double check to make sure they are correct?

**Comment by asheeshiit** [comment]
**Uckeys analysis on 3 month data and bucket_id 786**
I have done analysis on uckeys on 3 month data and bucket_id 786. i am sharing my statistics
PFA: 
[uckey_analysis_90_days_bucket_id_786.xlsx](https://github.com/Futurewei-io/blue-marlin/files/4324605/uckey_analysis_90_days_bucket_id_786.xlsx)

**Comment by xun-hu-at-futurewei-com** [comment]
Based on the discuss we had today, the code we saw is using the internal hash() method of python which gives us different value every time it runs.

Our intention is to use sha256 hash not the python internal hash()

sample code as following:

import hashlib

# this is the right function
def  my_hash_sha256(s):
    hex_value = hashlib.sha256(s.encode('utf-8')).hexdigest()
    return int(hex_value,16)

s = 'asheesh'
# the following gives different results
print(hash(s))

# this gives same result every time which is the good one, the result is integer
print(my_hash_sha256(s))

===========
Next step:
1) Replace hash function with hash_sha256 function
2) regenerate the whole FACTDATA with the new code
3) get several buckets data of FACTDATA
4) review the buckets data
5) run pipeline to generate the data for model and train the model
6) verify the model

**Comment by asheeshiit** [comment]
We have verified the my_hash_sha256 function . It is giving the desired results .Currently Working on correction of FACTDATA

**Comment by asheeshiit** [comment]
i have done data analysis on splash slot id .I am sharing my findings and code 

[30 Day analysis.docx](https://github.com/Futurewei-io/blue-marlin/files/4599207/30.Day.analysis.docx)

**Comment by xun-hu-at-futurewei-com** [comment]
We did some analysis on the recently 6 months data, we found some major issues with the data.

1) Based on my understanding, the number of regions is around 81. However we found many rows in FACTDATA with more than 81 as region number. Here are some examples:

splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,28,9 | 2/21/2020 | 1
-- | -- | --
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,150 | 2/21/2020 | 1
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,150 | 2/22/2020 | 2
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280 | 2/18/2020 | 5
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280 | 2/19/2020 | 1
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280 | 2/22/2020 | 10
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280 | 2/24/2020 | 9
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280 | 2/26/2020 | 12
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280 | 2/27/2020 | 3
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280 | 2/28/2020 | 6
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280 | 2/29/2020 | 1
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,324 | 2/18/2020 | 1
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,324 | 2/26/2020 | 1
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281, | 2/28/2020 | 2
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281, | 2/29/2020 | 1
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,26 | 2/27/2020 | 1
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281 | 2/18/2020 | 2
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281 | 2/20/2020 | 1
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281 | 2/21/2020 | 2
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281 | 2/22/2020 | 5
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281 | 2/24/2020 | 3
splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281 | 2/26/2020 | 3

The maximum value of ipl is 339. 
This caused a huge problem,  this will make FACTDATA very sparse and will not be able to train our model.

2) We might not need ipl as part of uckey at all as it is not valuable for inventory search and booking.

We need to have a discuss on this issue in our weekly meeting.

**Comment by asheeshiit** [comment]
> We did some analysis on the recently 6 months data, we found some major issues with the data.
> 
> 1. Based on my understanding, the number of regions is around 81. However we found many rows in FACTDATA with more than 81 as region number. Here are some examples:
> 
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,28,9	2/21/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,150	2/21/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,150	2/22/2020	2
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280	2/18/2020	5
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280	2/19/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280	2/22/2020	10
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280	2/24/2020	9
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280	2/26/2020	12
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280	2/27/2020	3
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280	2/28/2020	6
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,280	2/29/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,324	2/18/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,280,324	2/26/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,	2/28/2020	2
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,	2/29/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,26	2/27/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281	2/18/2020	2
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281	2/20/2020	1
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281	2/21/2020	2
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281	2/22/2020	5
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281	2/24/2020	3
> splash,15e9ddce941b11e5bdec00163e291137,4G,g_f,5,CPM,281,281	2/26/2020	3
> The maximum value of ipl is 339.
> This caused a huge problem, this will make FACTDATA very sparse and will not be able to train our model.
> 
> 1. We might not need ipl as part of uckey at all as it is not valuable for inventory search and booking.
> 
> We need to have a discuss on this issue in our weekly meeting.


ipl stands for **IP address location**?? (residence_city_region, city_code_region)

**Comment by Atlantis-s** [comment]
ipl means **current location**，and r means **permanent residence**   ：）

And maybe there is a misunderstanding here. Actually both ipl（current location） and r（permanent residence） will be used for inventory search and booking, but they will not be used at the same time, so ipl cannot be deleted from uckey.

**Comment by saritpg** [comment]
I took January 2020 data. Filtered it for the slot ids. Also edited the region code. Removed city code (as either current city or permanent residence will be used at a given time). Created time series data for these uckeys. Now, took a random sample of 10% of these uckeys-time series data. Here is my analysis:

"times series data" = for 30 days time series data points, how many of them are non-zero values.
"% of total" = % of uckeys from total with such time series data.

![image](https://user-images.githubusercontent.com/12243267/82286395-41cb5480-99bb-11ea-938f-94985961d715.png)

As can be seen, 67% of the uckeys contains less than 10% non-zero time series data.

**Comment by saritpg** [comment]
I analyzed the Jan 2020 dataset. First, I filtered the dataset for the slot ids. Thereafter, the current_region id was edited for correct id values. The permanent_residence id was dropped (as for a given query, either current_region or permanent_residence will be used).

With this dataset, here are the results:

time series data = % of non-zero time series datapoints in this 30 day data for each uckey.
% uckeys of total = % of uckeys with this time series data distribution.

![image](https://user-images.githubusercontent.com/12243267/82306478-b9f64200-99dc-11ea-8c3b-d2eef4298656.png)

As you can see, 40% of the uckeys have less than 10% time series data.
61% of the uckeys have less than 30% time series data (very sparse)

**Comment by asheeshiit** [comment]
I have trained the model and compare the predict impression with the actual impression 
My Findings : 

1. Time series (key=uckey-hour-price_cat) ,having low standard deviation(impression) -> ,**predicted  impression count are more closer to actual impression count** 

2. Time series (key=uckey-hour-price_cat) ,having higher standard deviation(impression) -> ,predicted  more inaccurate results . On the hand its contribution to total impression is more than (50%)

I am sharing the standard deviation analysis  (top 100 keys having highest contribution in impression count, date range : 1-Nov-2019 to 31-Jan-2020 )  

PFA

[std_analysis.pdf](https://github.com/Futurewei-io/blue-marlin/files/4696200/std_analysis.pdf)
