### ISSUE TITLE
The relationship between different tables

### ISSUE THREAD

**Issue by xun-hu-at-futurewei-com** [Futurewei-io/blue-marlin#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xun-hu-at-futurewei-com** [comment]
To make our future DIN model work, we need to get the following tables:
1) impression log file (table: impression)
2) click log file (table: click)
3) user profile (table: ads_persona)

A couple of questions:
1) What is column to link impression and log tables?
2) In impression and click tables, which column to get ads related information?
3) We are missing ads table or creative table or some other table to link with. How can we get ads related information from impression and click table?

**Comment by blue-tigo** [comment]
> 1. What is column to link impression and log tables?
'log_id' is related to the impression and other events long. From ad request to events report is all same log_id.

> 2. In impression and click tables, which column to get ads related information?
adv_prim_id is related to advertiserId
order_id is related to an campaign
task_id is related to a contract,  t_task_content(creative) also has a task_id, which can make a relationship.

> 3. We are missing ads table or creative table or some other table to link with. How can we get ads related information from impression and click table?
I will share more schemes to describe ads information. Can enumerate which ads attribute model needs?  Logs schemes have comments to describe each column.
