### ISSUE TITLE
unable to load saved model for prediction

### ISSUE THREAD

**Issue by saritpg** [Futurewei-io/blue-marlin#36]
I am trying to load the saved model (saved through save_model.py) using the following code:

import tensorflow as tf
model_path = "/home/sarit/blue-marlin/Model/predictor_dl_model/predictor_dl_model/data/vars/2/" 
with tf.Session(graph=tf.Graph()) as sess:
    tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], model_path) 

It returns the following error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-20-30ccb27e2fc3> in <module>
      1 with tf.Session(graph=tf.Graph()) as sess:
----> 2     tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], model_path)
      3 

~/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    322               'in a future version' if date is None else ('after %s' % date),
    323               instructions)
--> 324       return func(*args, **kwargs)
    325     return tf_decorator.make_decorator(
    326         func, new_func, 'deprecated',

~/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py in load(sess, tags, export_dir, import_scope, **saver_kwargs)
    267   """
    268   loader = SavedModelLoader(export_dir)
--> 269   return loader.load(sess, tags, import_scope, **saver_kwargs)
    270 
    271 

~/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py in load(self, sess, tags, import_scope, **saver_kwargs)
    420     with sess.graph.as_default():
    421       saver, _ = self.load_graph(sess.graph, tags, import_scope,
--> 422                                  **saver_kwargs)
    423       self.restore_variables(sess, saver, import_scope)
    424       self.run_init_ops(sess, tags, import_scope)

~/.local/lib/python3.6/site-packages/tensorflow/python/saved_model/loader_impl.py in load_graph(self, graph, tags, import_scope, **saver_kwargs)
    350     with graph.as_default():
    351       return tf_saver._import_meta_graph_with_return_elements(  # pylint: disable=protected-access
--> 352           meta_graph_def, import_scope=import_scope, **saver_kwargs)
    353 
    354   def restore_variables(self, sess, saver, import_scope=None):

~/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py in _import_meta_graph_with_return_elements(meta_graph_or_file, clear_devices, import_scope, return_elements, **kwargs)
   1471           import_scope=import_scope,
   1472           return_elements=return_elements,
-> 1473           **kwargs))
   1474 
   1475   saver = _create_saver_from_imported_meta_graph(meta_graph_def, import_scope,

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py in import_scoped_meta_graph_with_return_elements(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate, return_elements)
    855         input_map=input_map,
    856         producer_op_list=producer_op_list,
--> 857         return_elements=return_elements)
    858 
    859     # TensorFlow versions before 1.9 (not inclusive) exported SavedModels

~/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py in new_func(*args, **kwargs)
    505                 'in a future version' if date is None else ('after %s' % date),
    506                 instructions)
--> 507       return func(*args, **kwargs)
    508 
    509     doc = _add_deprecated_arg_notice_to_docstring(

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    398   if producer_op_list is not None:
    399     # TODO(skyewm): make a copy of graph_def so we're not mutating the argument?
--> 400     _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
    401 
    402   graph = ops.get_default_graph()

~/.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py in _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
    158     # Remove any default attr values that aren't in op_def.
    159     if node.op in producer_op_dict:
--> 160       op_def = op_dict[node.op]
    161       producer_op_def = producer_op_dict[node.op]
    162       # We make a copy of node.attr to iterate through since we may modify

KeyError: 'GRUBlockCell'

############################

Please let me know where exactly I am going wrong in loading this model or what the correct code should be.

**Comment by zqlao** [comment]
Can you upload the model (including 'saved_model.pb' file and 'variables' sub-fold) so that I can duplicate the issue?
Thanks.

**Comment by saritpg** [comment]
> Can you upload the model (including 'saved_model.pb' file and 'variables' sub-fold) so that I can duplicate the issue?
> Thanks.


[saved_model.zip](https://github.com/Futurewei-io/blue-marlin/files/4473189/saved_model.zip)


[variables_index.zip](https://github.com/Futurewei-io/blue-marlin/files/4473221/variables_index.zip)

**Comment by zqlao** [comment]
GRUBlockCell needs to be imported in order to load the model, please add:

from tensorflow.contrib.rnn import GRUBlockCell
