### ISSUE TITLE
Documentation of predictor_dl_model module is missing

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#5]
Logic is quite complex to understand .Would you please upload the detail document of predictor_dl_model module and its limitations.

**Comment by xun-hu-at-futurewei-com** [comment]
Yes, we will schedule a discuss session next Monday PST. We will publish the detail today. Thanks for checking.

**Comment by zhentiwei** [comment]
Where did you put the document details?  we are not able to see the detail ?
and can you please share us the session link in advance ?
Thanks for sharing.

**Comment by jimmylao** [comment]
[model-intro.v1.pdf](https://github.com/Futurewei-io/blue-marlin/files/4129729/model-intro.v1.pdf)
The basic structure of the model follows seq2seq. A typical application of the model is used to language translation (Chinese -> English for example). There are 2 major components of the model: encoder and decoder. Please find the attached pdf file for a brief description of the model and major functions corresponding to encoder & decoder in the model.py.
