### ISSUE TITLE
Initial testing result with new data

### ISSUE THREAD

**Issue by jimmylao** [Futurewei-io/blue-marlin#68]
Data Pre-processing:
--------------------------
1. aggregate daily data, every price category is regarded as a separate row
2. data cleaning: excluding rows that meet with the 2 criteria as follows
   a. popularity <= 5
   b. popularity > mean(popularity) & the percentage of non-zero data point of the row<= 15%

3. dense and sparse rows separation. If a certain row's normalized popularity < 0.01 or the percentage of non-zero data point of the row<0.5, it is treated as a sparse row.
4. converting sparse row clusters into virtual dense row
   a. randomly shuffle the order of sparse rows in order to evenly distribute data pattern (large and small) across all sparse rows
  b. estimate the total number of virtual dense rows: 
      m = int(ceil(dense_mean_popularity / sparse_median_popularity / 100.0) * 100)
  c. starting from the beginning of shuffled sparse row list and group every _m_ sparse rows into one virtual dense row (column-wise aggregation) until reaching the end of the sparse row list.
5. merge dense rows and virtual dense rows for training

Configurations   
--------------------
Here are some configuration when running trainer.py
1. trainer related configuration in config.yml 
=================================
trainer:
  name: 's32' 
  hparam_set: 's32' 
  n_models: 1 
  multi_gpu: false 
  seed: 5 
  logdir: 'data/logs' 
  max_epoch: 345 
  patience: 2 
  train_sampling: 1.0 
  eval_sampling: 1.0 
  eval_memsize: 15 
  gpu: 0 
  gpu_allow_growth: false 
  save_best_model: true 
  forward_split: false 
  side_split: false 
  do_eval: false 
  write_summaries: true 
  verbose: false 
  asgd_decay: 0.99 
  tqdm: true 
  max_steps: 80000 
  save_from_step: 100 
  predict_window: 10
=================================
[config.txt](https://github.com/Futurewei-io/blue-marlin/files/5307948/config.txt)

2. s32 related configuration in hparams.py
=================================
params_s32 = dict(
    batch_size=300, 
    train_window=70,
    train_skip_first=0,
    rnn_depth=500, 
    use_attn=False,
   \# use_attn=True,
    attention_depth=60,
    attention_heads=10,
    encoder_readout_dropout=0.4768781146510798,

    encoder_rnn_layers=1,
    decoder_rnn_layers=1,

    decoder_input_dropout=[1.0, 1.0, 1.0],
    decoder_output_dropout=[0.975, 1.0, 1.0],  
    decoder_state_dropout=[0.99, 0.995, 0.995],  
    decoder_variational_dropout=[False, False, False],
    decoder_candidate_l2=0.0,
    decoder_gates_l2=0.0,

    fingerprint_fc_dropout=0.8232342370695286,
    gate_dropout=0.9967589439360334, 
    gate_activation='none',
    encoder_dropout=0.030490422531402273,
    encoder_stability_loss=0.0,  
    encoder_activation_loss=1e-06, 
    decoder_stability_loss=0.0, 
    decoder_activation_loss=5e-06, 
)
=================================
[hparams.txt](https://github.com/Futurewei-io/blue-marlin/files/5307951/hparams.txt)

Testing result
------------------------
MAPE is used as an error metric of testing, the overall error got is 0.12. Here is the evolution of the error curve of testing data with various epochs.
![image](https://user-images.githubusercontent.com/60371672/94614866-d51f6b00-0274-11eb-9c96-d168831a4cd4.png)

**Comment by asheeshiit** [comment]
@jimmylao would please share the testing results , so that we can compare the prediction results?

**Comment by jimmylao** [comment]
Please find the detailed MAPE error information for each epoch as well as each batch in the excel file attached. The error curve is also included in the attached file.
[test_error.xlsx](https://github.com/Futurewei-io/blue-marlin/files/5388349/test_error.xlsx)

**Comment by asheeshiit** [comment]
After updating current DL code ( as per the new doc ),we are getting following error curve 
![image](https://user-images.githubusercontent.com/8120966/96875332-b89dd980-1494-11eb-8823-ded3044b6d3d.png)

Our error value is converging to 0.12

**Comment by jimmylao** [comment]
Looks good. Thanks for sharing. 
Can you share the error data file used to plot the curve?

**Comment by asheeshiit** [comment]
@jimmylao Please find dl error data 

[dl_error.txt](https://github.com/Futurewei-io/blue-marlin/files/5423552/dl_error.txt)

**Comment by jimmylao** [comment]
@asheeshiit
In addition to the total number of epoch you modified while training the model, did you modify the following parameters?
in hparams.py:
batch_size
train_window

in config.yml:
duration in tfrecorder_reader section
predict_window in trainer section
