### ISSUE TITLE
Logic behind the highlighted code??

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#7]
**Please explain the logic behind the highlighted code**
![image](https://user-images.githubusercontent.com/8120966/73234015-525a8380-41ae-11ea-93b8-ee044167c118.png)

**Comment by jimmylao** [comment]
the function of the highlighted code is the same as
![image](https://user-images.githubusercontent.com/60371672/73384540-73e46980-4299-11ea-85b5-99b1d640e084.png)
RNN = cudnn_rnn.CudnnGRU, the purpose of this function is to build a rnn encoder (single or multiple layers), the operator (cudnn_rnn.CudnnGRU) is defined in cudnn and run pretty fast.
However, while freezing trained checkpoint model (.meta (graph) + .data (weights))to .pb file, there’s an error. This has been one of the issues posted on tensorflow’s github site (https://github.com/tensorflow/tensorflow/issues/23898) by other tensorflow developers and is believed to be a bug in tensorflow (https://stackoverflow.com/questions/53817487/how-to-restore-cudnn-lstm).
The operator that is currently using (cudnn_rnn.CudnnCompatibleGRUCell) is a compatible operator to cudnn_rnn.CudnnGRU that solve the problem mentioned above.
