### ISSUE TITLE
Code compatibility issue, as per the latest analysis document

### ISSUE THREAD

**Issue by sanjaynirmal** [Futurewei-io/blue-marlin#70]
As per the latest analysis document (Price category will be the part of Uckey and have dropped residence city id from uckey)
New formula for UCKEY=adv_type,slot_id,net_type,gender,age,pricing_type, city_code_region,price_cat

We are facing code compatibility issue in following modules
1)data preprocessing
2) training 
eg.
![e_1](https://user-images.githubusercontent.com/40193781/96339597-6125f500-10b3-11eb-890e-2d36282dd3fc.png)

3)predictor
eg.
![e_2](https://user-images.githubusercontent.com/40193781/96339623-89155880-10b3-11eb-8e35-35fbeab96027.png)

we are in project deployment phase .it would be of great help to us, if team blue-marlin update the code as per the latest analysis document

**Comment by asheeshiit** [comment]
we have observer that if we append the **price_cat** into uckey , we have to update multiple scripts of DL module. 
Please update the DL module code.

**Comment by radibnia77** [comment]
price_cat is not part of uckey. 
uckey consists of the following item based on latest code.
```
 ucdoc.m = parts[0] #media-type
 ucdoc.si = parts[1] #slot-id
 ucdoc.t = parts[2] #connection-type
 ucdoc.g = parts[3]#gender
 ucdoc.a = parts[4]#age
ucdoc.pm = parts[5]#price-model
ucdoc.r = parts[6]#resident-location
ucdoc.ipl = parts[7]#ip-location
```
