### ISSUE TITLE
The query of code/document update

### ISSUE THREAD

**Issue by zhentiwei** [Futurewei-io/blue-marlin#75]
Kindly please your team check and confirm currently source code and document are the latest till now 22nd Oct. 2020.

Thank you very much 👍

**Comment by xun-hu-at-futurewei-com** [comment]
https://github.com/Futurewei-io/blue-marlin/blob/master/Dataset_Analysis/new_factdata_processing.github.v1.pdf

The document has been changed and uploaded.

**Comment by zhentiwei** [comment]
Great, It is very detail 👍
