### ISSUE TITLE
city analysis

### ISSUE THREAD

**Issue by Atlantis-s** [Futurewei-io/blue-marlin#82]
hi guys，I analyzed the resident cities and the current city proportions of three days in October, September, and August in the historical data. We can discuss these data in the meeting. Data are as follows:
[city analysis.xlsx](https://github.com/Futurewei-io/blue-marlin/files/5458993/city.analysis.xlsx)
![city](https://user-images.githubusercontent.com/54946393/97586727-90365200-1a35-11eb-881a-2b22a9b8bc0b.PNG)

**Comment by xun-hu-at-futurewei-com** [comment]
Did you use FACTDATA table or Log table?

**Comment by Atlantis-s** [comment]
> Did you use FACTDATA table or Log table?

I use FACTDATA，Log table don‘t have resident city.

**Comment by xun-hu-at-futurewei-com** [comment]
You need join with persona table to get resident city. Let us discuss it today.
