### ISSUE TITLE
Input and output variable explanation ??

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#9]
**Please explain the Input variable and output variables of current  model **
![image](https://user-images.githubusercontent.com/8120966/73235900-4a064680-41b6-11ea-89a6-743d61b8d33e.png)

**Comment by jimmylao** [comment]
please find attached pdf file for the evolution of variables including training & validation splitting, pre-processing, normalization, batches serialization, etc.
input values defined above {laggedx, normmean, normstd, normx, normy, page_features, pageix, timex, timey, truex, truey} correspond to the last variable list before "model".
laggedx: variable used to compute quarter autocorrelation
normmean: mean used for normalization
normstd: stand deviation used for normalization
normx: normalized training time series data
normy: normalized validation time series data
page_features: set of property features including age, si, network, gender, price_cat, page_popularity, quarter_autocorr
pageix: identity string for each row
timex: full set of features used for training including norm_x_hits, x_dow, x_lagged, pf_age, pf_si, pf_network, pf_gender, pf_price_cat, page_popularity, quarter_autocorrr
timey: full set of features used for validation including y_dow, y_lagged, pf_age, pf_si, pf_network, pf_gender, page_popularity, quarter_autocorr
truex: ground truth training time series data
truey: ground truth validation time series data

there's only 1 output variable defined: pred (time series prediction for the future)

**Comment by jimmylao** [comment]
[model-input-variable-intro.pdf](https://github.com/Futurewei-io/blue-marlin/files/4131275/model-input-variable-intro.pdf)
here is the input variable introduction pdf file mentioned above
