### ISSUE TITLE
DIN: Measure of common interests in group of users

### ISSUE THREAD

**Issue by rangaswamymr** [Futurewei-io/blue-marlin#91]
The basic assumption to use GDIN ( group DIN) is that the group of users in data are sharing common interests or behavior. Is there a method/metric to measure the commonality in group of users in the given data samples? 
 Did you measure the commonality in your sample data before applying DIN?

**Comment by xun-hu-at-futurewei-com** [comment]
Yes, this assumption is our model's base. Our PF based on GDIN model is an good example to demonstrate that our assumption is correct. Please check the report generated by Jimmy regarding performance of GDIN model.

**Comment by jimmylao** [comment]
Please find the GDIN testing report attached.
[GDIN_testing_report.pdf](https://github.com/Futurewei-io/blue-marlin/files/5745415/GDIN_testing_report.pdf)

**Comment by rangaswamymr** [comment]
@xun-hu-at-futurewei-com @jimmylao , thank you for your comments.
Can you please clarify the source of CTR data in test report? is it calculated with help of showlog and clicklogs tables used in training the model or its a completely new set of data used for model testing purpose?

**Comment by jimmylao** [comment]
The purpose of the GDIN model is to predict GUER's (group of users) future behavior (click) based on their historical behavior (impression or click).
The data used in the test report is logdata, i.e. showlog, clicklog, and persona. A pre-defined cutting date is used to split the whole dataset into training and testing subsets, i.e. data before the cutting date was used as training while data after the cutting date was used as testing.
