### ISSUE TITLE
Datatype mismatch issue

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#92]
@jimmylao  We are trying to run DIN using the same data, which was shared by the Litiange with blue-marlin team.  But we are facing fields data type mismatch issue.
Please confirm ,if you have used same data for DIN or you have done some data preprocessing before loading showlog, clicklog and persona data in hive
Ex. I am sharing one of the instance, where we are getting exception due to datatype miss-match 
In click_log table,  click_time field data type is string 
 
![image](https://user-images.githubusercontent.com/8120966/103208524-d53c0f00-4926-11eb-93f8-c68c04ea394d.png)

But In code, we are executing hive query based on timestamp. which is causing a issue ( no data is return )
 
![image](https://user-images.githubusercontent.com/8120966/103208512-d2411e80-4926-11eb-810d-7a918042f3f3.png)

**If any some data preprocessing scripts is exist , please share with US**

**Comment by radibnia77** [comment]
Can you please share the schema of your click-log table (some relevant fields) and an example of a record?
