### ISSUE TITLE
[DIN] Raw_impressions are hard coded 

### ISSUE THREAD

**Issue by asheeshiit** [Futurewei-io/blue-marlin#99]
Can you please explain why why raw_impressions are hard coded within fit_distribution function( within main_logs_with_regions.py script) and what fit_distribution function is doing in the DIN

![image](https://user-images.githubusercontent.com/8120966/103648827-78be9c80-4f83-11eb-9438-0294db1a7190.png)

**Comment by asheeshiit** [comment]
@spyglass700 to calculate the raw_impressions, What are the different regions I need to consider and what should be the time interval

**Comment by radibnia77** [comment]
main_logs_with_regions.py is used for testing purposes when the input log data does not contain residency/region information.  This code is to inject region information based on pre-calculated raw-impressions.  This file should not used in production environment.
